OnlineStore/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from OnlineStore import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('delivery/', include('delivery.urls')),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),
    path('', include('store.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from cart.views import *

app_name = 'cart'


urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('checkout', checkout, name='cart_checkout'),
    path('clear/', cart_clear, name='cart_clear'),
    path('add/<int:product_id>/',
         cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         cart_remove,
         name='cart_remove'),
]

store/urls.py
from django.urls import path

from store.views import *

urlpatterns = [
    path('', index, name='store_index'),
    path('shop', shop, name="shop"),
    path('shop/<int:id>', product, name="product"),
    path('shop/other', shopOther, name="other"),
    path('shop/female', shopFeMale, name="female"),
    path('shop/male', shopMale, name="male"),
    path('blog', blog, name="blog"),
    path('order', orders, name="order"),
    path('order/detail/<int:id>', detail),
    # products
    path('add-product/', admin_add_product, name='add_product'),
    path('products/<int:pk>', update_product, name='update_product'),
    path('products/', admin_products, name='admin_products'),
    # blog
    path('blog-list/', admin_blog_list, name='admin_blog_list'),
    path('add-blog/', add_blog_admin, name='add_blog_admin'),
    path('update-blog/<int:pk>', update_blog_admin, name='update_blog_admin'),
    path('delete-blog-admin/<int:pk>', delete_blog_admin, name='delete_blog_admin'),
    # orders
    path('order-list/', order_list_admin, name='order_list_admin'),
    path('order-detail-list/<int:pk>', order_detail_list_admin, name='order_detail_list'),

]

cart/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models

from account.models import User


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Status(models.Model):
    name = models.CharField(max_length=255)
    percent = models.FloatField(default=0)

    def __str__(self):
        return self.name


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.IntegerField(default=0)
    img1 = models.ImageField(upload_to='images/', blank=True, null=True)
    img2 = models.ImageField(upload_to='images/', blank=True, null=True)
    img3 = models.ImageField(upload_to='images/', blank=True, null=True)
    img4 = models.ImageField(upload_to='images/', blank=True, null=True)
    img5 = models.ImageField(upload_to='images/', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING, blank=True, null=True)
    status = models.ForeignKey(Status, on_delete=models.DO_NOTHING, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class OrderStatus(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.CharField(max_length=50, blank=True, null=True)
    address1 = models.CharField(max_length=50, blank=True, null=True)
    address2 = models.CharField(max_length=50, blank=True, null=True)
    phone = models.CharField(max_length=50, blank=True, null=True)
    lat = models.CharField(max_length=50, blank=True, null=True)
    lng = models.CharField(max_length=50, blank=True, null=True)
    status = models.ForeignKey(OrderStatus, on_delete=models.DO_NOTHING, blank=True, null=True, default=1)
    delivery = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='delivery',
                                 verbose_name='delivery')

    def __str__(self):
        return self.user.name


class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.CharField(max_length=50, blank=True, null=True)
    count = models.CharField(max_length=50, blank=True, null=True)
    total_price = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.order.user.name + " " + self.product.name


class Blog(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)
    creat_at = models.DateField(auto_now_add=True)
    description = models.TextField()
    img = models.ImageField(upload_to='images/', blank=True, null=True)

    def __str__(self):
        return self.name

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 5)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int
                                      )

    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput
                                )

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.views.decorators.http import require_POST

from cart.cart import Cart
from cart.forms import CartAddProductForm
from store.models import Product, Order, OrderDetail


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'store/cart.html', {'cart': cart, "count": cart.__len__()})


def checkout(request):
    cart = Cart(request)

    if cart.get_total_price() == 0:
        return redirect('cart:cart_detail')

    if request.method == "POST":
        address1 = request.POST['address1']
        address2 = request.POST['address2']
        phone = request.POST['phone']
        lat = request.POST['lat']
        lng = request.POST['lng']
        #
        # print(lat)
        # print(lng)

        context = {
            "address1": address1,
            "address2": address2,
            "phone": phone,
            'cart': cart,
            "count": cart.__len__()
        }

        if lat == '51.176461847963516' and lng == '71.40863847220683':
            context['error'] = 'Подтвердите адрес из карты'
            return render(request, 'store/checkout.html', context=context)

        order = Order.objects.create(user=request.user, total=cart.get_total_price(),
                                     address1=address1, address2=address2, phone=phone,
                                     lat=lat, lng=lng)

        order.save()

        for item in cart:
            # print(item)
            # order = Order.objects.get(id=order.id)
            product = Product.objects.get(id=item['product'].id)
            order_detail = OrderDetail.objects.create(order=order, product=product,
                                                      price=item['price'], count=item['quantity'],
                                                      total_price=item['total_price'])

            order_detail.save()

        cart = Cart(request)
        cart.clear()

        return redirect('/order')

    return render(request, 'store/checkout.html', {'cart': cart, "count": cart.__len__()})

store/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

# Create your views here.
from cart.cart import Cart
from cart.forms import CartAddProductForm
from store.models import *


@login_required(login_url='/account/logining')
def index(request):
    user = request.user
    role = user.roles
    cart = Cart(request)
    products = Product.objects.all()
    blog = Blog.objects.all()[:2]

    return render(request, 'store/index.html', context={"role": role, "list": products, "cart": cart, "count":  cart.__len__(), "blog": blog})


@login_required(login_url='/account/logining')
def shop(request):
    user = request.user
    role = user.roles

    products = Product.objects.all()

    cart_product_form = CartAddProductForm()
    cart = Cart(request)

    blog = Blog.objects.all()[:2]

    context = {
        "list": products,
        "cart_product_form": cart_product_form,
        "cat": "all",
        "cart": cart,
        "count": cart.__len__(),
        "blog": blog,
    }
    return render(request, 'store/categories.html', context=context)


@login_required(login_url='/account/logining')
def shopOther(request):
    user = request.user
    role = user.roles

    cart = Cart(request)
    products = Product.objects.filter(category__name="Другое")
    blog = Blog.objects.all()[:2]

    context = {
        "list": products,
        "cat": "other",
        "cart": cart,
        "count": cart.__len__(),
        "blog": blog,
    }
    return render(request, 'store/categories.html', context=context)


@login_required(login_url='/account/logining')
def shopFeMale(request):
    user = request.user
    role = user.roles
    cart = Cart(request)
    products = Product.objects.filter(category__name="Женский")
    blog = Blog.objects.all()[:2]

    context = {
        "list": products,
        "cat": "female",
        "cart": cart,
        "count": cart.__len__(),
        "blog": blog,
    }
    return render(request, 'store/categories.html', context=context)


@login_required(login_url='/account/logining')
def shopMale(request):
    user = request.user
    role = user.roles
    cart = Cart(request)
    products = Product.objects.filter(category__name="Мужской")
    blog = Blog.objects.all()[:2]

    context = {
        "list": products,
        "cat": "muj",
        "cart": cart,
        "count": cart.__len__(),
        "blog": blog,
    }
    return render(request, 'store/categories.html', context=context)


@login_required(login_url='/account/logining')
def product(request, id):
    user = request.user
    role = user.roles

    product = Product.objects.get(id=id)
    list = Product.objects.filter(category=product.category)
    cart_product_form = CartAddProductForm()
    cart = Cart(request)
    blog = Blog.objects.all()[:2]

    context = {
        "product": product,
        "list": list,
        "cart_product_form": cart_product_form,
        "cat": "all",
        "cart": cart,
        "count": cart.__len__(),
        "blog": blog,
    }
    return render(request, 'store/product.html', context=context)


@login_required(login_url='/account/logining')
def blog(request):
    user = request.user
    role = user.roles
    cart = Cart(request)
    blog = Blog.objects.all()

    context = {
        'cart': cart,
        "count": cart.__len__(),
        "blogs": blog,
        "blog": blog[:2],
    }
    return render(request, 'store/blog.html', context=context)


@login_required(login_url='/account/logining')
def orders(request):
    user = request.user
    role = user.roles

    cart = Cart(request)
    order = Order.objects.filter(user=user).order_by('-pk')
    blog = Blog.objects.all()[:2]

    context = {
        'order': order,
        'cart': cart,
        "count": cart.__len__(),
        "blog": blog,
    }
    return render(request, 'store/Orders.html', context=context)


@login_required(login_url='/account/logining')
def detail(request, id):
    user = request.user
    role = user.roles
    cart = Cart(request)
    order = Order.objects.get(id=id)
    detail = OrderDetail.objects.filter(order=order)
    blog = Blog.objects.all()[:2]

    context = {
        'order': order,
        'detail': detail,
        'cart': cart,
        "count": cart.__len__(),
        "blog": blog,
    }
    return render(request, 'store/orderdetail.html', context=context)


@login_required(login_url='/account/logining')
def admin_add_product(request):
    if request.method == "POST":
        data = request.POST
        name = data.get('name')
        price = data.get('price')
        description = data.get('description')
        category = data.get('category')
        status = data.get('status')
        files = request.FILES
        img1 = files.get('img1')
        img2 = files.get('img2')
        img3 = files.get('img3')
        img4 = files.get('img4')
        img5 = files.get('img5')
        product = Product.objects.create(
            name=name, price=price, description=description, category_id=category, status_id=status,
            img1=img1, img2=img2, img3=img3, img4=img4, img5=img5
        )

        return render(request, 'admin/add-product.html', {"segment": "products"})

    if request.method == "GET":
        categories = Category.objects.all()
        statuses = Status.objects.all()
        context = {
            'categories': categories,
            'statuses': statuses,
            "segment": "products",
            'action': 'Өнімді қосыңыз'
        }
        return render(request, 'admin/add-product.html', context)


@login_required(login_url='/account/logining')
def admin_products(request):
    list = Product.objects.all().order_by('-pk')
    return render(request, 'admin/products.html', {'list': list, "segment": "products"})


def update_product(request, pk):
    if request.method == "GET":
        categories = Category.objects.all()
        statuses = Status.objects.all()
        product = Product.objects.get(pk=pk)
        return render(request, 'admin/add-product.html', {"segment": "products", 'product': product, 'categories': categories,
            'statuses': statuses, 'action': 'Өнімді жаңартыңыз'})

    if request.method == "POST":
        if request.method == "POST":
            data = request.POST
            name = data.get('name')
            price = data.get('price')
            description = data.get('description')
            category = data.get('category')
            status = data.get('status')
            files = request.FILES
            img1 = files.get('img1')
            img2 = files.get('img2')
            img3 = files.get('img3')
            img4 = files.get('img4')
            img5 = files.get('img5')

            product = Product.objects.get(pk=pk)
            product.name = name
            product.price = price
            product.description = description
            product.category_id = category
            product.status_id = status
            if img5:product.img5 = img5
            if img4:product.img4 = img4
            if img3:product.img3 = img3
            if img2:product.img2 = img2
            if img1:product.img1 = img1
            product.save()

            return redirect('admin_products')

def admin_blog_list(request):
    list = Blog.objects.all().order_by('-pk')
    return render(request, 'admin/blogs.html', {'list': list, "segment": "blog"})


def add_blog_admin(request):
    if request.method == "GET":
        return render(request, 'admin/add-blog.html', {"segment": "blog", 'action': 'Блог қосу'})

    if request.method == "POST":
        name = request.POST.get('name')
        description = request.POST.get('description')
        img = request.FILES.get('img')

        blog = Blog.objects.create(name=name, img=img, description=description)

        return redirect('admin_blog_list')


def update_blog_admin(request, pk):
    if request.method == "POST":
        name = request.POST.get('name')
        description = request.POST.get('description')
        img = request.FILES.get('img')
        print(img)
        blog = Blog.objects.get(pk=pk)
        blog.name = name
        blog.description = description
        if img:
            blog.img = img
        blog.save()

        return redirect('admin_blog_list')

    if request.method == "GET":
        blog = Blog.objects.get(pk=pk)
        name = blog.name
        description = blog.description
        img = blog.img
        return render(request, 'admin/add-blog.html', {'name': name, 'description': description, 'img': img,
                                                       'segment': 'blog', 'action': 'Блогты жаңартыңыз'})


def delete_blog_admin(request, pk):
    try:
        del_sel = Blog.objects.get(pk=pk)
    except id.DoesNotExist:
        return redirect('admin_blog_list')
    del_sel.delete()
    return redirect('admin_blog_list')


def order_list_admin(request):
    list = Order.objects.all()
    return render(request, 'admin/Orders.html', {'list': list, "segment": "order"})


def order_detail_list_admin(request, pk):
    order = Order.objects.get(pk=pk)
    list = OrderDetail.objects.filter(order=order)
    return render(request, 'admin/order-details.html', {'order': order, 'list': list, "segment": "order"})

templates/store/cart.html
{% extends 'store/base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="../../static/styles/cart.css">
    <link rel="stylesheet" type="text/css" href="../../static/styles/cart_responsive.css">
{% endblock %}
{% block content %}

	<!-- Home -->

	<div class="home">
		<div class="parallax_background parallax-window" data-parallax="scroll" data-image-src="{% static 'images/product_background.jpg' %}" data-speed="0.8"></div>
		<div class="home_container">
			<div class="home_content">
				<div class="home_title">Корзина</div>
				<div class="breadcrumbs">
					<ul class="d-flex flex-row align-items-center justify-content-start">
						<li><a href="/">Главная</a></li>
						<li>Корзина</li>
					</ul>
				</div>
			</div>
		</div>
	</div>


	<!-- Cart -->

	<div class="cart_section">
		<div class="section_container">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="cart_container">
							
							<!-- Cart Bar -->
							<div class="cart_bar">
								<ul class="cart_bar_list item_list d-flex flex-row align-items-center justify-content-start">
									<li>Фото</li>
									<li>Цена</li>
									<li>Количество</li>
									<li>Изменить</li>
									<li>Общая сумма</li>
									<li>Удалить</li>
								</ul>
							</div>

							<!-- Cart Items -->
							<div class="cart_items">
								<ul class="cart_items_list">
                                {% for item in cart %}
                                    {% with product=item.product %}
									<!-- Cart Item -->
                                    <li class="cart_item item_list d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-start">
										<div class="product d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-start">
                                            <div>
                                                <div class="product_image">
                                                    <img src="/media/{{ product.img1 }}" alt="">
                                                </div>
                                            </div>
											<div class="product_name">
                                                <a href="product.html">{{ product.name }}</a>
                                            </div>
										</div>


										<div class="product_price text-lg-center product_text"><span>Price: </span>{{ item.price }} тнг</div>
										<div class="product_quantity_container">
											<div class="product_quantity ml-lg-auto mr-lg-auto text-center">
												<span class="product_text product_num">{{ item.quantity }}</span>
{#												<div class="qty_sub qty_button trans_200 text-center"><span>-</span></div>#}
{#												<div class="qty_add qty_button trans_200 text-center"><span>+</span></div>#}
											</div>
										</div>
                                        <div class="product_size text-lg-center product_text">
                                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                                    {{ item.update_quantity_form.quantity }}
                                                    {{ item.update_quantity_form.update }}
                                                    <input type="submit" value="Обновить" style="background-color: transparent;border: none; color: #0c5460">
                                                    {% csrf_token %}
                                                  </form>
                                        </div>
										<div class="product_total text-lg-center product_text"><span>Total: </span>{{ item.total_price }} тнг</div>

                                        <div class="product_color text-lg-center product_text">
                                            <a href="{% url 'cart:cart_remove' product.id %}">Удалить</a>
                                        </div>
									</li>
							         {% endwith %}
                                {% endfor %}
                                </ul>
							</div>

							<!-- Cart Buttons -->
							<div class="cart_buttons d-flex flex-row align-items-start justify-content-start">
								<div class="cart_buttons_inner ml-auto d-flex flex-row align-items-start justify-content-start flex-wrap">
									<div class="button button_continue trans_200"><a href="/shop">Продолжать покупку</a></div>
									<div class="button button_clear trans_200"><a href="{% url 'cart:cart_clear'  %}">очищать корзину </a></div>
{#									<div class="button button_update trans_200"><a href="categories.html">update cart</a></div>#}
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="section_container cart_extra_container">
			<div class="container">
				<div class="row">
					<!-- Cart Total -->
                    <div class="col-xxl-3"></div>
					<div class="col-xxl-6">
						<div class="cart_extra cart_extra_2">
							<div class="cart_extra_content cart_extra_total">
								<div class="cart_extra_title">Всего в корзине</div>
								<ul class="cart_extra_total_list">
									<li class="d-flex flex-row align-items-center justify-content-start">
										<div class="cart_extra_total_title">Промежуточный итог</div>
										<div class="cart_extra_total_value ml-auto">{{ cart.get_total_price }} тнг</div>
									</li>
									<li class="d-flex flex-row align-items-center justify-content-start">
										<div class="cart_extra_total_title">Доставка</div>
										<div class="cart_extra_total_value ml-auto">Бесплатно</div>
									</li>
									<li class="d-flex flex-row align-items-center justify-content-start">
										<div class="cart_extra_total_title">Общее</div>
										<div class="cart_extra_total_value ml-auto">{{ cart.get_total_price }} тнг</div>
									</li>
								</ul>
								<div class="checkout_button trans_200"><a href="checkout">Купить</a></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/store/index.html
{% extends 'store/base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles/main_styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/responsive.css' %}">
    <style>
    .product_tag {
        width: 81px;
    }
    </style>
{% endblock %}
{% block content %}

	<div class="home">

		<!-- Home Slider -->
		<div class="home_slider_container">
			<div class="owl-carousel owl-theme home_slider">

				<!-- Slide -->
				<div class="owl-item">
					<div class="background_image" style="background-image:url(../../static/images/home_slider_1.jpg)"></div>
					<div class="home_content_container">
						<div class="home_content">
							<div class="home_discount d-flex flex-row align-items-end justify-content-start">
								<div class="home_discount_num">20</div>
								<div class="home_discount_text">жеңілдік</div>
							</div>
							<div class="home_title">Жаңа</div>
							<div class="button button_1 home_button trans_200"><a href="/shop">Қазір сатып алу!</a></div>
						</div>
					</div>
				</div>

				<!-- Slide -->
				<div class="owl-item">
					<div class="background_image" style="background-image:url(../../static/images/home_slider_1.jpg)"></div>
					<div class="home_content_container">
						<div class="home_content">
							<div class="home_discount d-flex flex-row align-items-end justify-content-start">
								<div class="home_discount_num">20</div>
								<div class="home_discount_text">жеңілдік</div>
							</div>
							<div class="home_title">Жаңа</div>
							<div class="button button_1 home_button trans_200"><a href="/shop">Қазір сатып алу!</a></div>
						</div>
					</div>
				</div>

				<!-- Slide -->
				<div class="owl-item">
					<div class="background_image" style="background-image:url(../../static/images/home_slider_1.jpg)"></div>
					<div class="home_content_container">
						<div class="home_content">
							<div class="home_discount d-flex flex-row align-items-end justify-content-start">
								<div class="home_discount_num">20</div>
								<div class="home_discount_text">жеңілдік</div>
							</div>
							<div class="home_title">Жаңа</div>
							<div class="button button_1 home_button trans_200"><a href="/shop">Қазір сатып алу!</a></div>
						</div>
					</div>
				</div>

			</div>

			<!-- Home Slider Navigation -->
			<div class="home_slider_nav home_slider_prev trans_200"><div class=" d-flex flex-column align-items-center justify-content-center"><img src="../../static/images/prev.png" alt=""></div></div>
			<div class="home_slider_nav home_slider_next trans_200"><div class=" d-flex flex-column align-items-center justify-content-center"><img src="../../static/images/next.png" alt=""></div></div>

		</div>
	</div>

	<!-- Boxes -->

	<div class="boxes">
		<div class="section_container">
			<div class="container">
				<div class="row">

					<!-- Box -->
					<div class="col-lg-4 box_col">
						<div class="box">
							<div class="box_image"><img src="../../static/images/box_1.jpg" alt=""></div>
							<div class="box_title trans_200"><a href="categories.html">жазғы коллекциялар</a></div>
						</div>
					</div>

					<!-- Box -->
					<div class="col-lg-4 box_col">
						<div class="box">
							<div class="box_image"><img src="../../static/images/box_2.jpg" alt=""></div>
							<div class="box_title trans_200"><a href="categories.html">көзілдірік коллекциясы</a></div>
						</div>
					</div>

					<!-- Box -->
					<div class="col-lg-4 box_col">
						<div class="box">
							<div class="box_image"><img src="../../static/images/box_3.jpg" alt=""></div>
							<div class="box_title trans_200"><a href="categories.html">негізгі бөліктер</a></div>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>

	<!-- Categories -->

	<div class="categories">
		<div class="section_container">
			<div class="container">
				<div class="row">
					<div class="col text-center">
						<div class="categories_list_container">
							<ul class="categories_list d-flex flex-row align-items-center justify-content-start">
								<li><a href="{% url 'male' %}">Ерлердікі</a></li>
								<li><a href="{% url 'female' %}">Әйелдер</a></li>
								<li><a href="{% url 'other' %}">Басқа</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Products -->

	<div class="products">
		<div class="section_container">
			<div class="container">
				<div class="row">
					<div class="col">
						<div class="products_container grid">

							{% for l in list %}
                                <div class="product grid-item
                                    {% if 'Топ' in l.status.name  %}hot {% endif %}
                                    {% if 'Скидка' in l.status.name  %}sale {% endif %}
                                    {% if 'Новый' in l.status.name  %} new {% endif %}">
                                    <div class="product_inner">
                                        <div class="product_image">
                                            <a href="{% url 'product' l.id %}">
                                                <img src="/media/{{ l.img1 }}" alt="">
                                            </a>

                                            <div class="product_tag">
                                                {% if 'Топ' in l.status.name  %}Топ {% endif %}
                                                {% if 'Скидка' in l.status.name  %}  Жеңілдік {% endif %}
                                                {% if 'Новый' in l.status.name  %} Жаңа {% endif %}
                                            </div>
                                        </div>
                                        <div class="product_content text-center">
                                            <div class="product_title"><a href="product.html">{{ l.name }}</a></div>
                                            <div class="product_price">{{ l.price }} тнг</div>
                                            <div class="product_button ml-auto mr-auto trans_200" style="width: 200px;">
                                                <form action="{% url 'cart:cart_add' l.id %}" method="POST">
                                                    <select name="quantity" id="id_quantity" style="display: none">
                                                        <option value="1" selected></option>
{#                                                        {% for l in cart_product_form %}#}
{#                                                            <option value="l.value"></option>#}
{#                                                        {%  endfor %}#}
                                                    </select>
                                                    {% csrf_token %}
                                                    <input type="submit" value="Кәрзеңкеге қосу" style="background-color: transparent; border: none; padding: 10px;">
                                                </form>
{#                                                <a href="#">add to cart</a>#}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


	<!-- Footer -->

{% endblock %}